import Link from "next/link";
import { Archive, CreditCard, Landmark, Pencil, Trash2, TrendingUp, WalletCards } from "lucide-react";
import { getCurrentHousehold } from "@/lib/household";
import { formatMoney } from "@/lib/finance/money";
import { TransactionForm } from "@/components/transactions/transaction-form";
import type { Account, Category } from "@/types/database";
import { archiveAccount, createAccount } from "../cuentas/actions";
import { softDeleteTransaction } from "../actions";

type AccountRow={id:string;name:string;type:string;current_balance_cents:number};
type TransactionRow={id:string;type:"expense"|"income";amount_cents:number;description:string;transaction_date:string;categories:{name:string}|null};

export default async function PersonalPage({searchParams}:{searchParams:Promise<{created?:string;error?:string}>}){
  const params=await searchParams; const {supabase,user,household}=await getCurrentHousehold(); if(!household)return null;
  const now=new Date(); const monthStart=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-01`; const nextMonth=new Date(Date.UTC(now.getFullYear(),now.getMonth()+1,1)).toISOString().slice(0,10);
  const [{data:accountsData},{data:transactionsData},{data:summaryData},{data:categoriesData}]=await Promise.all([
    supabase.from("accounts").select("id,name,type,current_balance_cents").eq("household_id",household.id).eq("owner_user_id",user.id).eq("is_shared",false).is("archived_at",null).order("name"),
    supabase.from("transactions").select("id,type,amount_cents,description,transaction_date,categories(name)").eq("household_id",household.id).eq("created_by",user.id).eq("scope","personal").eq("status","confirmed").order("transaction_date",{ascending:false}).order("created_at",{ascending:false}).limit(30),
    supabase.from("transactions").select("type,amount_cents").eq("household_id",household.id).eq("created_by",user.id).eq("scope","personal").eq("status","confirmed").gte("transaction_date",monthStart).lt("transaction_date",nextMonth),
    supabase.from("categories").select("id,name,kind,icon,color").or(`household_id.eq.${household.id},household_id.is.null`).order("name"),
  ]);
  const accounts=(accountsData??[]) as AccountRow[]; const transactions=(transactionsData??[]) as unknown as TransactionRow[];
  const summary=(summaryData??[]) as {type:"expense"|"income";amount_cents:number}[]; const income=summary.filter(row=>row.type==="income").reduce((sum,row)=>sum+row.amount_cents,0); const expenses=summary.filter(row=>row.type==="expense").reduce((sum,row)=>sum+row.amount_cents,0);
  return <><div><p className="text-sm font-bold uppercase">Privado para ti</p><h1 className="mt-1 text-3xl font-black md:text-4xl">Mi espacio personal</h1><p className="mt-3 max-w-2xl text-[#3a3434]/75">Tus cuentas y movimientos individuales no se muestran a otros miembros. Tu bot sí puede consultarlos junto con las finanzas compartidas.</p></div>
    {params.created&&<p className="mt-5 rounded-xl bg-[#87cd64] p-3 text-sm font-bold">Movimiento personal guardado.</p>}{params.error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}
    <section className="mt-7 grid grid-cols-2 gap-3"><article className="rounded-sm border border-[#3a3434]/20 bg-[#87cd64] p-5"><p className="w-fit bg-[#ffff50] px-1 text-xs font-bold uppercase">Ingresos personales · mes</p><p className="mt-2 text-2xl font-black">{formatMoney(income)}</p></article><article className="rounded-sm border border-[#3a3434]/20 bg-[#ff6e7d] p-5"><p className="w-fit bg-[#ffff50] px-1 text-xs font-bold uppercase">Gastos personales · mes</p><p className="mt-2 text-2xl font-black">{formatMoney(expenses)}</p></article></section>
    <div className="mt-7 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="card p-6"><h2 className="text-xl font-black">Mis cuentas</h2><div className="mt-5 space-y-3">{accounts.map(account=><article className="flex items-center gap-3 border-b border-black/10 pb-3" key={account.id}><span className="grid size-10 place-items-center rounded-xl bg-[#73c8dc]">{account.type==="cash"?<WalletCards size={19}/>:account.type==="card"?<CreditCard size={19}/>:account.type==="investment"?<TrendingUp size={19}/>:<Landmark size={19}/>}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{account.name}</p><p className="text-sm">{formatMoney(account.current_balance_cents)}</p></div><form action={archiveAccount}><input type="hidden" name="id" value={account.id}/><button aria-label={`Archivar ${account.name}`} className="rounded-lg p-2"><Archive size={17}/></button></form></article>)}{!accounts.length&&<p className="text-sm text-[#6c7f7a]">Crea tu primera cuenta personal para comenzar.</p>}</div><form action={createAccount} className="mt-6 grid gap-4"><h3 className="font-black">Nueva cuenta personal</h3><label><span className="label">Nombre</span><input className="field" name="name" required placeholder="Mi tarjeta"/></label><div className="grid grid-cols-2 gap-3"><label><span className="label">Tipo</span><select className="field" name="type"><option value="bank">Banco</option><option value="card">Tarjeta</option><option value="cash">Efectivo</option><option value="savings">Ahorros</option><option value="investment">Inversión</option></select></label><label><span className="label">Saldo inicial</span><input className="field" name="balance" inputMode="decimal" placeholder="0,00"/></label></div><button className="rounded-xl px-5 py-3 font-bold">Crear cuenta</button></form></section>
      <section className="card p-6"><h2 className="text-xl font-black">Nuevo movimiento personal</h2><TransactionForm mode="personal" accounts={accounts as Pick<Account,"id"|"name">[]} categories={(categoriesData??[]) as Category[]}/></section></div>
    <section className="card mt-7 overflow-hidden"><div className="border-b border-black/10 px-5 py-4"><h2 className="font-black">Movimientos personales recientes</h2></div>{transactions.map(row=><article key={row.id} className="flex items-center gap-3 border-b border-black/10 p-4 last:border-0"><div className="min-w-0 flex-1"><p className="truncate font-bold">{row.description}</p><p className="text-xs text-[#6c7f7a]">{row.categories?.name??"Sin categoría"} · {row.transaction_date}</p></div><b>{row.type==="expense"?"−":"+"}{formatMoney(row.amount_cents)}</b><Link href={`/app/movimientos/${row.id}/editar`} aria-label={`Editar ${row.description}`} className="rounded-lg p-2"><Pencil size={17}/></Link><form action={softDeleteTransaction}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="returnTo" value="/app/personal"/><button aria-label={`Eliminar ${row.description}`} className="rounded-lg p-2"><Trash2 size={17}/></button></form></article>)}{!transactions.length&&<p className="p-10 text-center text-sm text-[#6c7f7a]">Todavía no hay movimientos personales.</p>}</section>
  </>;
}
