import Link from "next/link";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { getCurrentHousehold } from "@/lib/household";
import { formatMoney } from "@/lib/finance/money";
import { softDeleteTransaction } from "../actions";

type Row = { id:string; created_by:string; type:"expense"|"income"; amount_cents:number; description:string; transaction_date:string; scope:string; categories:{name:string}|null; accounts:{name:string}|null };
export default async function TransactionsPage({ searchParams }: { searchParams: Promise<{ q?: string; type?: string; error?: string }> }) {
  const params=await searchParams; const {supabase,user,household}=await getCurrentHousehold(); if(!household)return null;
  let query=supabase.from("transactions").select("id,created_by,type,amount_cents,description,transaction_date,scope,categories(name),accounts(name)").eq("household_id",household.id).eq("scope","shared").eq("status","confirmed").order("transaction_date",{ascending:false}).limit(50);
  if(params.q) query=query.ilike("description",`%${params.q.replace(/[%_]/g,"")}%`); if(params.type==="expense"||params.type==="income") query=query.eq("type",params.type);
  const {data}=await query; const rows=(data??[]) as unknown as Row[];
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#6c7f7a]">Todo en un sitio</p><h1 className="text-3xl font-black">Movimientos</h1></div><Link href="/app/movimientos/nuevo" className="flex items-center gap-2 rounded-xl bg-[#26725c] px-4 py-3 text-sm font-bold text-white"><Plus size={18}/>Nuevo movimiento</Link></div>
  {params.error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}<form className="card mt-6 flex flex-col gap-3 p-4 sm:flex-row"><input className="field flex-1" name="q" defaultValue={params.q} placeholder="Buscar por descripción…"/><select className="field sm:w-44" name="type" defaultValue={params.type??""}><option value="">Todos</option><option value="expense">Gastos</option><option value="income">Ingresos</option></select><button className="rounded-xl border border-[#cad7d2] px-5 py-2.5 font-bold">Filtrar</button></form>
  <section className="card mt-5 overflow-hidden"><div className="hidden grid-cols-[1fr_140px_120px_130px_76px] gap-4 border-b border-black/5 px-6 py-3 text-xs font-bold uppercase tracking-wide text-[#6c7f7a] md:grid"><span>Descripción</span><span>Categoría</span><span>Fecha</span><span className="text-right">Importe</span><span/></div>{rows.map(row=><article key={row.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-black/5 p-4 last:border-0 md:grid-cols-[1fr_140px_120px_130px_76px] md:items-center md:px-6"><div><p className="font-bold">{row.description}</p><p className="text-xs text-[#6c7f7a] md:hidden">{row.categories?.name} · {row.transaction_date}</p><span className="mt-1 inline-block rounded-full bg-[#eef2ef] px-2 py-0.5 text-[10px] font-bold">{row.scope==="shared"?"Compartido":"Personal"}</span></div><span className="hidden text-sm md:block">{row.categories?.name}</span><span className="hidden text-sm text-[#6c7f7a] md:block">{row.transaction_date}</span><b className={`text-right ${row.type==="income"?"text-[#26725c]":""}`}>{row.type==="expense"?"−":"+"}{formatMoney(row.amount_cents)}</b>{row.created_by===user.id?<div className="flex"><Link href={`/app/movimientos/${row.id}/editar`} aria-label={`Editar ${row.description}`} className="rounded-lg p-2 text-[#9aaaa5] hover:bg-[#dceee6] hover:text-[#26725c]"><Pencil size={17}/></Link><form action={softDeleteTransaction}><input type="hidden" name="id" value={row.id}/><button aria-label={`Eliminar ${row.description}`} className="rounded-lg p-2 text-[#9aaaa5] hover:bg-red-50 hover:text-red-600"><Trash2 size={17}/></button></form></div>:<span/>}</article>)}{!rows.length&&<div className="p-14 text-center"><p className="font-bold">No hay movimientos</p><p className="mt-1 text-sm text-[#6c7f7a]">Prueba otros filtros o añade el primero.</p></div>}</section></>;
}
