import Link from "next/link";
import { Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { getCurrentHousehold } from "@/lib/household";
import { formatMoney } from "@/lib/finance/money";
import { softDeleteTransaction } from "../actions";

type Row = { id:string; created_by:string; created_at:string; type:"expense"|"income"; amount_cents:number; description:string; transaction_date:string; scope:string; categories:{name:string}|null; accounts:{name:string}|null };
type MemberRow = { user_id:string; profiles:{display_name:string|null}|null };

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<{ q?: string; type?: string; error?: string }> }) {
  const params=await searchParams; const {supabase,user,household}=await getCurrentHousehold(); if(!household)return null;
  let query=supabase.from("transactions").select("id,created_by,created_at,type,amount_cents,description,transaction_date,scope,categories(name),accounts(name)").eq("household_id",household.id).eq("scope","shared").eq("status","confirmed").order("transaction_date",{ascending:false}).order("created_at",{ascending:false}).limit(50);
  const search=params.q?.trim(); if(search)query=query.ilike("description",`%${search.replace(/[%_]/g,"")}%`); if(params.type==="expense"||params.type==="income")query=query.eq("type",params.type);
  const [{data},{data:membersData}]=await Promise.all([query,supabase.from("household_members").select("user_id,profiles(display_name)").eq("household_id",household.id)]);
  const rows=(data??[]) as unknown as Row[]; const members=(membersData??[]) as unknown as MemberRow[]; const memberNames=new Map(members.map(member=>[member.user_id,member.profiles?.display_name??"Miembro"])); const hasFilters=Boolean(search||params.type);

  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#6c7f7a]">Todo en un sitio</p><h1 className="text-3xl font-black">Movimientos</h1></div><Link href="/app/movimientos/nuevo" className="flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold"><Plus size={18}/>Nuevo movimiento</Link></div>
    {params.error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{params.error}</p>}
    <form className="card mt-6 p-5"><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_180px_auto] md:items-end"><label><span className="label">Buscar movimiento</span><div className="relative"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#6e6464]" size={17}/><input className="field pl-11" name="q" defaultValue={search} placeholder="Supermercado, alquiler…"/></div></label><label><span className="label">Tipo</span><select className="field" name="type" defaultValue={params.type??""}><option value="">Todos</option><option value="expense">Gastos</option><option value="income">Ingresos</option></select></label><div className="flex gap-2"><button className="min-h-12 flex-1 rounded-xl px-5 py-2.5 font-bold md:flex-none">Aplicar filtros</button>{hasFilters&&<Link href="/app/movimientos" aria-label="Limpiar filtros" data-button-theme="inverse" className="grid min-h-12 min-w-12 place-items-center rounded-xl"><X size={18}/></Link>}</div></div></form>
    <section className="card mt-5 overflow-hidden"><div className="hidden grid-cols-[minmax(0,1.2fr)_130px_120px_105px_125px_76px] gap-4 border-b border-black/10 px-6 py-3 text-xs font-bold uppercase tracking-wide text-[#6c7f7a] lg:grid"><span>Descripción</span><span>Registrado por</span><span>Categoría</span><span>Fecha</span><span className="text-right">Importe</span><span/></div>{rows.map(row=>{const creator=memberNames.get(row.created_by)??"Miembro";return <article key={row.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 border-b border-black/10 p-4 last:border-0 lg:grid-cols-[minmax(0,1.2fr)_130px_120px_105px_125px_76px] lg:items-center lg:px-6"><div className="min-w-0"><p className="truncate font-bold">{row.description}</p><p className="mt-1 text-xs text-[#6c7f7a] lg:hidden">{row.categories?.name??"Sin categoría"} · {row.transaction_date}</p><p className="mt-1 text-xs font-bold lg:hidden">Registrado por {creator}</p></div><span className="hidden truncate text-sm font-bold lg:block">{creator}</span><span className="hidden truncate text-sm lg:block">{row.categories?.name??"Sin categoría"}</span><span className="hidden text-sm text-[#6c7f7a] lg:block">{row.transaction_date}</span><b className={`self-start text-right lg:self-auto ${row.type==="income"?"text-[#26725c]":""}`}>{row.type==="expense"?"−":"+"}{formatMoney(row.amount_cents)}</b>{row.created_by===user.id?<div className="col-start-2 flex justify-end lg:col-auto"><Link href={`/app/movimientos/${row.id}/editar`} aria-label={`Editar ${row.description}`} className="rounded-lg p-2"><Pencil size={17}/></Link><form action={softDeleteTransaction}><input type="hidden" name="id" value={row.id}/><button aria-label={`Eliminar ${row.description}`} className="rounded-lg p-2"><Trash2 size={17}/></button></form></div>:<span/>}</article>})}{!rows.length&&<div className="p-14 text-center"><p className="font-bold">No hay movimientos</p><p className="mt-1 text-sm text-[#6c7f7a]">Prueba otros filtros o añade el primero.</p></div>}</section>
  </>;
}
