import Link from "next/link";
import { ArrowDownLeft, ArrowUpRight, Plus } from "lucide-react";
import { getCurrentHousehold } from "@/lib/household";
import { formatMoney } from "@/lib/finance/money";
import { SummaryCard } from "@/components/dashboard/summary-card";
import { CategoryChart } from "@/components/charts/category-chart";

type DashboardRow = { id:string; type:"expense"|"income"; amount_cents:number; description:string; transaction_date:string; scope:"personal"|"shared"; categories:{name:string}|null };
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ month?: string; created?: string }> }) {
  const params = await searchParams; const now = new Date(); const fallback = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`; const month = /^\d{4}-\d{2}$/.test(params.month ?? "") ? params.month! : fallback;
  const [year, monthNumber] = month.split("-").map(Number); const start = `${month}-01`; const end = new Date(Date.UTC(year, monthNumber, 1)).toISOString().slice(0,10);
  const { supabase, household } = await getCurrentHousehold(); if (!household) return null;
  const { data } = await supabase.from("transactions").select("id,type,amount_cents,description,transaction_date,scope,categories(name)").eq("household_id",household.id).eq("scope","shared").eq("status","confirmed").gte("transaction_date",start).lt("transaction_date",end).order("transaction_date",{ascending:false}).order("created_at",{ascending:false});
  const rows = (data ?? []) as unknown as DashboardRow[]; const income = rows.filter(r=>r.type==="income").reduce((s,r)=>s+r.amount_cents,0); const expenses = rows.filter(r=>r.type==="expense").reduce((s,r)=>s+r.amount_cents,0); const savings = income-expenses; const shared = rows.filter(r=>r.type==="expense"&&r.scope==="shared").reduce((s,r)=>s+r.amount_cents,0);
  const byCategory = new Map<string,number>(); rows.filter(r=>r.type==="expense").forEach(r=>{const name=r.categories?.name??"Otros"; byCategory.set(name,(byCategory.get(name)??0)+r.amount_cents)}); const chart=[...byCategory].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,7);
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#6c7f7a]">Resumen del hogar</p><h1 className="mt-1 text-3xl font-black tracking-tight md:text-4xl">Así va vuestro mes</h1></div><div className="flex gap-3"><form><input aria-label="Mes" className="field" type="month" name="month" defaultValue={month}/></form><Link href="/app/movimientos/nuevo" className="flex items-center gap-2 rounded-xl bg-[#26725c] px-4 py-3 text-sm font-bold text-white"><Plus size={18}/> <span className="hidden sm:inline">Añadir</span></Link></div></div>{params.created && <p className="mt-5 rounded-xl bg-[#dceee6] p-3 text-sm font-bold text-[#26725c]">Movimiento guardado y resumen actualizado.</p>}
  <section className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><SummaryCard label="Ingresos" value={formatMoney(income)} tone="green"/><SummaryCard label="Gastos" value={formatMoney(expenses)} tone="coral"/><SummaryCard label="Ahorro" value={formatMoney(savings)} tone="plain" detail={income ? `${Math.round(savings/income*100)} % de los ingresos` : "Sin ingresos este mes"}/><SummaryCard label="Compartido" value={formatMoney(shared)} tone="lilac"/></section>
  <section className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.9fr]"><article className="card p-5 md:p-7"><div><h2 className="text-lg font-black">Gastos por categoría</h2><p className="text-sm text-[#6c7f7a]">Dónde se está yendo el dinero</p></div><CategoryChart data={chart}/></article><article className="card p-5 md:p-7"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Últimos movimientos</h2><p className="text-sm text-[#6c7f7a]">Los más recientes del mes</p></div><Link href="/app/movimientos" className="text-sm font-bold text-[#26725c]">Ver todos</Link></div><div className="mt-5 divide-y divide-black/5">{rows.slice(0,6).map(row=><div key={row.id} className="flex items-center gap-3 py-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${row.type==="expense"?"bg-[#f7ddd4] text-[#b34f36]":"bg-[#dceee6] text-[#26725c]"}`}>{row.type==="expense"?<ArrowUpRight size={18}/>:<ArrowDownLeft size={18}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{row.description}</p><p className="text-xs text-[#6c7f7a]">{row.categories?.name??"Sin categoría"}</p></div><b className="text-sm">{row.type==="expense"?"−":"+"}{formatMoney(row.amount_cents)}</b></div>)}{!rows.length&&<p className="py-12 text-center text-sm text-[#6c7f7a]">Aún no hay movimientos. El primero se apunta en un minuto.</p>}</div></article></section></>;
}
